package domain

import (
	"fmt"
	"time"

	"github.com/uptrace/bun"
)

// === CONTEXT ===
// Purpose: Core Auction aggregate — the central domain type for the auction-service.
// Contains all business rules for auction lifecycle state transitions.
//
// === DATA / STATE ===
// Auction is a mutable struct. Status transitions are guarded by methods.
// Lifecycle: Pending -> Active -> (EndingSoon) -> Closed
// Created per-auction, persisted in Postgres, loaded/saved via AuctionRepository.

// AuctionStatus represents the lifecycle state of an auction.
type AuctionStatus string

const (
	StatusPending    AuctionStatus = "pending"
	StatusActive     AuctionStatus = "active"
	StatusEndingSoon AuctionStatus = "ending_soon"
	StatusClosed     AuctionStatus = "closed"
)

// Auction represents a single auction in the system.
type Auction struct {
	bun.BaseModel `bun:"table:auctions,alias:a"`

	ID           int64         `bun:",pk,autoincrement"`
	Title        string        `bun:",notnull"`
	Description  string        `bun:",notnull,default:''"`
	StartPrice   float64       `bun:",notnull"`
	CurrentPrice float64       `bun:",notnull"`
	Status       AuctionStatus `bun:",notnull,default:'pending'"`
	WinnerBotID  int64         `bun:",notnull,default:0"`
	StartTime    time.Time     `bun:",notnull"`
	EndTime      time.Time     `bun:",notnull"`
	CreatedAt    time.Time     `bun:",nullzero,notnull,default:current_timestamp"`
	UpdatedAt    time.Time     `bun:",nullzero,notnull,default:current_timestamp"`
}

// === BEHAVIOR: NewAuction ===
// Input: title, description, startPrice, duration
// Output: *Auction in Pending status, or error if data is invalid
// Preconditions: title non-empty, startPrice > 0, duration > 0
// Postconditions: Auction created with generated ID, status=pending, times set
// Edge Cases: empty title, zero/negative price, zero/negative duration

// NewAuction creates a new Auction in Pending status.
func NewAuction(title, description string, startPrice float64, duration time.Duration) (*Auction, error) {
	if title == "" {
		return nil, fmt.Errorf("%w: title is required", ErrInvalidAuctionData)
	}
	if startPrice <= 0 {
		return nil, fmt.Errorf("%w: start price must be positive", ErrInvalidAuctionData)
	}
	if duration <= 0 {
		return nil, fmt.Errorf("%w: duration must be positive", ErrInvalidAuctionData)
	}

	now := time.Now().UTC()
	return &Auction{
		// ID is auto-generated by Postgres (autoincrement).
		Title:        title,
		Description:  description,
		StartPrice:   startPrice,
		CurrentPrice: startPrice,
		Status:       StatusPending,
		StartTime:    now,
		EndTime:      now.Add(duration),
		CreatedAt:    now,
		UpdatedAt:    now,
	}, nil
}

// === BEHAVIOR: Activate ===
// Preconditions: status must be Pending
// Postconditions: status becomes Active, UpdatedAt refreshed

// Activate transitions a Pending auction to Active.
func (a *Auction) Activate() error {
	if a.Status != StatusPending {
		return fmt.Errorf("%w: cannot activate auction in %s status", ErrInvalidStatus, a.Status)
	}
	a.Status = StatusActive
	a.UpdatedAt = time.Now().UTC()
	return nil
}

// === BEHAVIOR: MarkEndingSoon ===
// Preconditions: status must be Active
// Postconditions: status becomes EndingSoon, UpdatedAt refreshed

// MarkEndingSoon transitions an Active auction to EndingSoon.
func (a *Auction) MarkEndingSoon() error {
	if a.Status != StatusActive {
		return fmt.Errorf("%w: cannot mark ending soon from %s status", ErrInvalidStatus, a.Status)
	}
	a.Status = StatusEndingSoon
	a.UpdatedAt = time.Now().UTC()
	return nil
}

// === BEHAVIOR: Close ===
// Preconditions: status must be Active or EndingSoon
// Postconditions: status becomes Closed, winner set, UpdatedAt refreshed
// Edge Cases: no winner (unsold auction) — winnerBotID and winningBid are zero values

// Close transitions an Active or EndingSoon auction to Closed.
func (a *Auction) Close(winnerBotID int64, winningBid float64) error {
	if a.Status != StatusActive && a.Status != StatusEndingSoon {
		return fmt.Errorf("%w: cannot close auction in %s status", ErrInvalidStatus, a.Status)
	}
	a.Status = StatusClosed
	a.WinnerBotID = winnerBotID
	if winningBid > 0 {
		a.CurrentPrice = winningBid
	}
	a.UpdatedAt = time.Now().UTC()
	return nil
}

// === BEHAVIOR: IsExpired ===
// Returns true if the current time is past EndTime and status is Active or EndingSoon.

// IsExpired returns true if the auction's end time has passed and it hasn't been closed yet.
func (a *Auction) IsExpired() bool {
	return (a.Status == StatusActive || a.Status == StatusEndingSoon) && time.Now().UTC().After(a.EndTime)
}

// === BEHAVIOR: IsEndingSoon ===
// Returns true if time remaining is within the threshold and status is Active.

// IsEndingSoon returns true if the auction is active and within the ending-soon threshold.
func (a *Auction) IsEndingSoon(threshold time.Duration) bool {
	if a.Status != StatusActive {
		return false
	}
	return time.Until(a.EndTime) <= threshold
}
